### ISSUE TITLE
You might want to fix this 

### ISSUE THREAD

**Issue by KermanIsPretty** [NamelessMC/Nameless-Java-API#5]
When friendly URLs are enabled, in the URL yours defaults to add a ? to the end of the request and the API for nameless does not like that took me 30 mins to figure out why it wasn't working. Maybe don't add ?'s to it only add &

**Comment by KermanIsPretty** [comment]
Line 60: in request `final char prefix = baseUrl.toString().contains("?") ? '&' : '?';`

Should be `final char prefix = "&";`

**Comment by Derkades** [comment]
In general friendly URLs do not work well with parameters and should probably not be used, but I will take a look
