### ISSUE TITLE
Method for post article with API

### ISSUE THREAD

**Issue by WatchAndyTW** [NamelessMC/Nameless-Java-API#6]
Hello, is there any ways to post an article with the API? I wanna to make a Discord Bot for automatically post article when admin entered a post command. Can anyone help?

**Comment by Derkades** [comment]
No, there is no such method currently available. v2 api documentation: <https://github.com/NamelessMC/Nameless/wiki/v2-API>

I have created an issue: https://github.com/NamelessMC/Nameless/issues/1623
